# Generated by Django 4.2.16 on 2024-12-10 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('instructions', models.TextField()),
                ('cooking_time', models.PositiveIntegerField()),
                ('serving_size', models.PositiveIntegerField()),
                ('image', models.ImageField(upload_to='recipes/')),
                ('category', models.CharField(choices=[('main', 'Main Course'), ('dessert', 'Dessert'), ('appetizer', 'Appetizer')], max_length=50)),
                ('ingredients', models.ManyToManyField(to='recipes.ingredient')),
            ],
        ),
    ]
